from backend.app.schemas.health import HealthResponse, ServiceStatus
from backend.app.schemas.vehicle import (
    VehicleBase,
    VehicleCreate,
    VehicleUpdate,
    VehicleRead,
    VehicleStatusSummary,
)
from backend.app.schemas.driver import (
    DriverBase,
    DriverCreate,
    DriverUpdate,
    DriverRead,
)
from backend.app.schemas.trip import (
    TripBase,
    TripCreate,
    TripUpdate,
    TripRead,
)
from backend.app.schemas.telemetry import (
    TelemetryPayload,
    TelemetryRead,
    TelemetryHistoryResponse,
    LatestTelemetryMap,
)
from backend.app.schemas.analytics import (
    DriverAnalyticsResponse,
    SafetyScoreResponse,
    AnomalyRecordResponse,
    AnomalyListResponse,
    VehicleHealthResponse,
    MaintenancePredictionResponse,
)
from backend.app.schemas.scenario import (
    ScenarioType,
    ScenarioTriggerRequest,
    ScenarioInfo,
    VehicleScenarioState,
    ScenarioStatusResponse,
)

from backend.app.schemas.alert import (
    AlertSeverity,
    AlertStatus,
    AlertType,
    AlertBase,
    AlertCreate,
    AlertUpdate,
    AlertRead,
    AlertSummaryCounts,
    AlertListResponse,
    AlertAcknowledgeRequest,
    AlertResolveRequest,
)
from backend.app.schemas.route import (
    Waypoint,
    OptimizedStop,
    RouteComparisonSummary,
    RouteOptimizeRequest,
    RouteOptimizeResponse,
    RouteRead,
    RouteListResponse,
    OptimizationGoal,
)

__all__ = [
    "HealthResponse",
    "ServiceStatus",
    "VehicleBase",
    "VehicleCreate",
    "VehicleUpdate",
    "VehicleRead",
    "VehicleStatusSummary",
    "DriverBase",
    "DriverCreate",
    "DriverUpdate",
    "DriverRead",
    "TripBase",
    "TripCreate",
    "TripUpdate",
    "TripRead",
    "TelemetryPayload",
    "TelemetryRead",
    "TelemetryHistoryResponse",
    "LatestTelemetryMap",
    "DriverAnalyticsResponse",
    "SafetyScoreResponse",
    "AnomalyRecordResponse",
    "AnomalyListResponse",
    "VehicleHealthResponse",
    "MaintenancePredictionResponse",
    "ScenarioType",
    "ScenarioTriggerRequest",
    "ScenarioInfo",
    "VehicleScenarioState",
    "ScenarioStatusResponse",
    "AlertSeverity",
    "AlertStatus",
    "AlertType",
    "AlertBase",
    "AlertCreate",
    "AlertUpdate",
    "AlertRead",
    "AlertSummaryCounts",
    "AlertListResponse",
    "AlertAcknowledgeRequest",
    "AlertResolveRequest",
    "Waypoint",
    "OptimizedStop",
    "RouteComparisonSummary",
    "RouteOptimizeRequest",
    "RouteOptimizeResponse",
    "RouteRead",
    "RouteListResponse",
    "OptimizationGoal",
]
